### ISSUE TITLE
can't build project using lib

### ISSUE THREAD

**Issue by Thelvaen** [revilo196/oscq_rs#1]
Hello,

I'm trying to build a project using your library, and it does not compile with a couple of issues on the services.

Attached below the errors I'm getting when trying to build.

thelvaen@penguin:~/lpd_hub$ cargo tauri dev
        Info Watching /home/thelvaen/lpd_hub/src-tauri for changes...
    Blocking waiting for file lock on build directory
   Compiling oscq_rs v0.0.2
error[E0053]: method `call` has an incompatible type for trait
  --> /home/thelvaen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/oscq_rs-0.0.2/src/service.rs:42:13
   |
42 |     fn call(&mut self, req: Request<IncomingBody>) -> Self::Future {
   |             ^^^^^^^^^
   |             |
   |             types differ in mutability
   |             help: change the self-receiver type to match the trait: `self: &OscQueryStatic`
   |
   = note: expected signature `fn(&OscQueryStatic, Request<_>) -> Pin<_>`
              found signature `fn(&mut OscQueryStatic, Request<_>) -> Pin<_>`

error[E0277]: the trait bound `tokio::net::TcpStream: hyper::rt::Read` is not satisfied
   --> /home/thelvaen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/oscq_rs-0.0.2/src/service.rs:141:39
    |
141 |                     .serve_connection(stream, service)
    |                      ---------------- ^^^^^^ the trait `hyper::rt::Read` is not implemented for `tokio::net::TcpStream`
    |                      |
    |                      required by a bound introduced by this call
    |
    = help: the following other types implement trait `hyper::rt::Read`:
              &mut T
              Box<T>
              Upgraded
note: required by a bound in `hyper::server::conn::http1::Builder::serve_connection`
   --> /home/thelvaen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.0.0-rc.4/src/server/conn/http1.rs:359:12
    |
353 |     pub fn serve_connection<I, S>(&self, io: I, service: S) -> Connection<I, S>
    |            ---------------- required by a bound in this associated function
...
359 |         I: Read + Write + Unpin,
    |            ^^^^ required by this bound in `Builder::serve_connection`

error[E0277]: the trait bound `tokio::net::TcpStream: hyper::rt::Write` is not satisfied
   --> /home/thelvaen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/oscq_rs-0.0.2/src/service.rs:141:39
    |
141 |                     .serve_connection(stream, service)
    |                      ---------------- ^^^^^^ the trait `hyper::rt::Write` is not implemented for `tokio::net::TcpStream`
    |                      |
    |                      required by a bound introduced by this call
    |
    = help: the following other types implement trait `hyper::rt::Write`:
              &mut T
              Box<T>
              Upgraded
note: required by a bound in `hyper::server::conn::http1::Builder::serve_connection`
   --> /home/thelvaen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.0.0-rc.4/src/server/conn/http1.rs:359:19
    |
353 |     pub fn serve_connection<I, S>(&self, io: I, service: S) -> Connection<I, S>
    |            ---------------- required by a bound in this associated function
...
359 |         I: Read + Write + Unpin,
    |                   ^^^^^ required by this bound in `Builder::serve_connection`

error[E0277]: the trait bound `tokio::net::TcpStream: hyper::rt::Read` is not satisfied
   --> /home/thelvaen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/oscq_rs-0.0.2/src/service.rs:142:22
    |
142 |                     .await
    |                     -^^^^^
    |                     ||
    |                     |the trait `hyper::rt::Read` is not implemented for `tokio::net::TcpStream`
    |                     help: remove the `.await`
    |
    = help: the following other types implement trait `hyper::rt::Read`:
              &mut T
              Box<T>
              Upgraded
    = note: required for `hyper::server::conn::http1::Connection<tokio::net::TcpStream, OscQueryStatic>` to implement `Future`
    = note: required for `hyper::server::conn::http1::Connection<tokio::net::TcpStream, OscQueryStatic>` to implement `IntoFuture`

error[E0277]: the trait bound `tokio::net::TcpStream: hyper::rt::Write` is not satisfied
   --> /home/thelvaen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/oscq_rs-0.0.2/src/service.rs:142:22
    |
142 |                     .await
    |                     -^^^^^
    |                     ||
    |                     |the trait `hyper::rt::Write` is not implemented for `tokio::net::TcpStream`
    |                     help: remove the `.await`
    |
    = help: the following other types implement trait `hyper::rt::Write`:
              &mut T
              Box<T>
              Upgraded
    = note: required for `hyper::server::conn::http1::Connection<tokio::net::TcpStream, OscQueryStatic>` to implement `Future`
    = note: required for `hyper::server::conn::http1::Connection<tokio::net::TcpStream, OscQueryStatic>` to implement `IntoFuture`

Some errors have detailed explanations: E0053, E0277.
For more information about an error, try `rustc --explain E0053`.
error: could not compile `oscq_rs` (lib) due to 5 previous errors

**Comment by DASPRiD** [comment]
Running into the same issues. I tried to fix them, but I'm kinda stumped there. @owalter-hab is this building for you?
